version: "3.7"

networks:
  internal:
    external: true

services:
  frontend:
    image: ghcr.io/projetointegradorstudy/condo-management-frontend:development
    container_name: frontend
    ports:
      - 3000:80
    networks:
      - internal
