export const USERS = [
  {
    id: '1',
    role: 'Admin',
    name: 'User 01',
    user_name: 'user01',
    avatar: 'https://github.com/projetointegradorstudy.png',
    registered_at: '20/05/23',
  },
  {
    id: '2',
    role: 'User',
    name: 'User 02',
    user_name: 'user02',
    avatar: 'https://github.com/nestjs.png',
    registered_at: '20/05/23',
  },
  {
    id: '3',
    role: 'Admin',
    name: 'User 03',
    user_name: 'user03',
    avatar: 'https://github.com/expressjs.png',
    registered_at: '20/05/23',
  },
  {
    id: '4',
    role: 'Admin',
    user_name: 'user04',
    name: 'User 04',
    avatar: 'https://github.com/prisma.png',
    registered_at: '20/05/23',
  },
  {
    id: '5',
    role: 'User',
    name: 'User 05',
    user_name: 'user05',
    avatar: 'https://github.com/docker.png',
    registered_at: '20/05/23',
  },
  {
    id: '6',
    role: 'User',
    user_name: 'user06',
    name: 'User 06',
    avatar: 'https://github.com/swagger-api.png',
    registered_at: '20/05/23',
  },
];
