name: CI-Development

on:
  pull_request:
    types:
      - closed
    branches:
      - "development"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  CI_Build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          echo "${{ vars.ENV_FILE }}" > .env

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          target: production
          push: false
          tags: |
            ghcr.io/infinit-pix/infinit-frontend:pr-${{github.run_number}}
